version: "2.1"

services:
    odoo:
        extends:
            file: common.yaml
            service: odoo
        build:
            args:
                # To aggregate in development, use `setup-devel.yaml`
                AGGREGATE: "false"
                # No need for this in development
                PIP_INSTALL_ODOO: "false"
                CLEAN: "false"
                COMPILE: "false"
        environment:
            ADMIN_PASSWORD: admin
            PGDATABASE: devel
            PYTHONOPTIMIZE: ""
            SMTP_PORT: "1025"
            # You want demo data for development
            WITHOUT_DEMO: "false"
        ports:
            - "127.0.0.1:${ODOO_MAJOR}069:8069"
            - "127.0.0.1:${ODOO_MAJOR}072:8072"
            - "127.0.0.1:6899:6899"
        volumes:
            - ./odoo/custom:/opt/odoo/custom:ro,z
            - ./odoo/auto/addons:/opt/odoo/auto/addons:rw,z
        depends_on:
            - db
            - smtp
            - wdb
        command:
            - odoo
            - --workers=0
            # XXX Odoo v8 has no `--dev` mode; Odoo v9 has no parameters
            - --dev=reload,qweb,werkzeug,xml,wdb

    db:
        extends:
            file: common.yaml
            service: db

    smtp:
        extends:
            file: common.yaml
            service: smtpfake
        ports:
            - "127.0.0.1:8025:8025"

    wdb:
        image: yajo/wdb-server
        ports:
            - "127.0.0.1:1984:1984"

networks:
    default:
        #internal: true
        internal: false

volumes:
    filestore:
    db:
